### ISSUE TITLE
Copyright and license headers stripped

### ISSUE THREAD

**Issue by guillemj** [jrmarino/libbsd4sol#2]
While checking the source code, I noticed that several copyright and license headers got stripped when importing the code? What happened?

**Comment by jrmarino** [comment]
Originally some were relocated to a separate license file.
However, you'd need to be specific on a file-by-file basis.  Many, many of the functions did not come from the linux libbsd but directly from other sources.  Probably most of the them actually.

**Comment by guillemj** [comment]
F.ex. src/getentropy_solaris.c, and many of the header files, f.ex. bsd/sys/cdefs.h, bsd/sys/tree.h, bsd/sys/endian.h, bsd/vis.h, etc.

**Comment by jrmarino** [comment]
so after a quick glance at a couple of those, I think this is what happened:
Originally, these files were included in the files section in part of a port, which all get concatenated on to a single file.  Since the license was duplicated, they were moved to a separate license file.  Then later this repository was created and the files copied over, so the copyright was basically lost.

For the headers that clearly came from libbsd, I can go back and replace them with current headers to restore the copyright info.  I'll try to get to it in a reasonable timeframe (I'm backed up and it's getting worse the longer I'm away from home this week).

**Comment by jrmarino** [comment]
actually, the headers are not an issue (headers not copywritable, supported by legal precedent https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.).  I'm checking all the source files though.
I'll check the headers too though and see if makes sense to add something back.

**Comment by jrmarino** [comment]
I'm putting notices back on headers with macros, e.g. sys/cdefs.h
